### ISSUE TITLE
Is it any different the koa ?

### ISSUE THREAD

**Issue by asafyish** [parro-it/comws#2]
Maybe you can differentiate by using Bluebird instead of co, which should be significantly faster.

**Comment by parro-it** [comment]
In my intent, it has not to differentiate from koa, because comws is born just to pick from koa the idea of generator middlewares chain to allow usage in any kind of application, not just web server.

Anyway, I'm really concerned with performance, and I really love Bluebird, so I'll try to make the change. 
Do you know if the performance gain is really significant? (I never use bluebird for such things)

**Comment by asafyish** [comment]
Oh, I didn't get that comws is a generic koa-like generator middleware.
I haven't done any benchmarks myself between bluebird and co, but, 
according to [this blog post](http://www.hiddentao.com/archives/2014/02/14/javascript-generator-delegation-and-coroutine-performance/) and many others, bluebird is much faster.

**Comment by parro-it** [comment]
Yes, as suggested on the dailyjs posts, a useful use case could be to add generators middlewares capability to an app already developed with express.
I will read the blog post, could bring to a useful improvement... thank you!

**Comment by parro-it** [comment]
@asafyish, I've prepared some benchmark. It appear that bluebird is actually slow than co, but maybe I'm doing something wrong (it is REALLY slower).
You can see [results here](https://github.com/shes/comws/tree/benchmark/bench). If you mind, please take a moment to peer review benchmark code, maybe I'm doing something wrong

**Comment by parro-it** [comment]
Close after a strong refactor, I don't mind so much on performance now. It will improve if needed
